#!/bin/bash

# Build the artifact
# Run with --no-cache to force a clean build of the docker image

# Better error handling
set -euxo pipefail

DOCKER_IMAGE_NAME=melt-umn-strategy-attributes.docker
TARBALL_NAME="2020_SLE_Strategy_Attributes.tar.gz"
CONTENTS_LIST="examples/ ../Step-By-Step-Instructions.md ../Getting-Started.md ../Abstract.txt ../paper.pdf"

echo "Deleting old examples..."
rm -rf examples/*

echo "Checking out examples..."
mkdir -p examples
cd examples
git clone -b v0.1.0 https://github.com/melt-umn/rewriting-optimization-demo.git
git clone -b v0.1.2 https://github.com/melt-umn/lambda-calculus.git
git clone -b v0.1.0 https://github.com/melt-umn/rewriting-regex-matching.git
git clone -b v0.1.1 https://github.com/melt-umn/ableC-halide.git

echo "Deleting unneeded files..."
rm -rf */.git */Jenkinsfile
cd ..

echo "Building docker image..."
docker build -t melt-umn/strategy-attributes . $@

echo "Saving docker image..."
docker save melt-umn/strategy-attributes -o $DOCKER_IMAGE_NAME

echo "Building artifact.tar.gz ..."
tar czf $TARBALL_NAME $DOCKER_IMAGE_NAME $CONTENTS_LIST
