#!/bin/bash

DOCKER_NAME=melt-umn/implicit-monads
DOCKER_IMAGE_NAME=melt-umn-implicit-monads.docker
DOCKERFILE_DIRECTORY=./Artifact-Docker

TARBALL_NAME="2020_SLE_AG_Monadification.tar.gz"
CONTENTS_LIST="../examples/ ../Step-By-Step-Instructions.md ../Getting-Started.md ../Authors.txt ../Abstract.txt ../preliminary-paper.pdf"



build_docker_image_clean () {
    docker build -t $DOCKER_NAME $DOCKERFILE_DIRECTORY --no-cache
}


build_docker_image () {
    docker build -t $DOCKER_NAME $DOCKERFILE_DIRECTORY
}


save_docker_image () {
    docker save $DOCKER_NAME -o $DOCKER_IMAGE_NAME
}



#Parse options
do_clean=false

while [ ! -z $1 ]; do
    case $1 in
        "--clean" ) do_clean=true ;; #rebuild everything completely
        x ) echo "Unknown option $x" ;;
    esac
    shift 1
done



#Check whether saved Docker image (the version that can be put directly in the tarball) exists
if [ -f $DOCKER_IMAGE_NAME ]; then
    docker_image_exists=true
else
    docker_image_exists=false
fi


#Building the Docker image and save it as appropriate
if [ $do_clean = true ]; then
    echo "***** Clean building Docker image $DOCKER_NAME *****"
    build_docker_image_clean
    echo ""
    echo "***** Saving Docker image to $DOCKER_IMAGE_NAME *****"
    save_docker_image
    echo ""
else if [ ! $docker_image_exists = true ]; then
         echo "***** Building Docker image $DOCKER_NAME *****"
         build_docker_image
         echo ""
         echo "***** Saving Docker image because saved Docker image $DOCKER_IMAGE_NAME does not exist. *****"
         save_docker_image
         echo ""
     fi
fi


#Build the tarball
echo "***** Building archive $TARBALL_NAME *****"
tar -c -f $TARBALL_NAME $DOCKER_IMAGE_NAME $CONTENTS_LIST



