#!/bin/bash

JARFILE=stlc.jar


if [ ! -f $JARFILE ]; then
    echo -e "\e[1;31mFile $JARFILE not found; building it\e[m"
    if ! ./silver-compile; then #exit on Silver compiler error
        exit 1
    fi
    echo ""
fi

echo -e -n "\e[4;32mEnter an expression:\e[m  "
read entered

while [ -n "$entered" ]; do
    java -jar $JARFILE "$entered"
    echo ""
    echo ""
    echo -e -n "\e[4;32mEnter an expression:\e[m  "
    read entered
done

echo ""
